USE [UANL]



--EXECUTE insertStudentSchedule 1000, 'LICENCIADO EN SEGURIDAD EN TECNOLOGIAS DE INFORMACION', 1, 'GUAJARDO', 'GARCIA', 'ELIZABETH', 'ÁLGEBRA', '07:00-07:30;07:30-08:00;'

--EXECUTE getAvailableSchedules 'LICENCIADO EN SEGURIDAD EN TECNOLOGIAS DE INFORMACION', 'ÁLGEBRA'

EXECUTE getClassroomFromSchedule 'LICENCIADO EN SEGURIDAD EN TECNOLOGIAS DE INFORMACION', 'GUAJARDO', 'GARCIA', 'ELIZABETH', 'ÁLGEBRA', '07:00-07:30;07:30-08:00;'

DELETE * FROM StudentSchedule


