USE [UANL]

/*
DROP TABLE Logs
DROP TABLE StudentSchedule
DROP TABLE Kardex
DROP TABLE Schedule
DROP TABLE SemesterSubject
DROP TABLE Student
DROP TABLE Teacher
DROP TABLE Career
DROP TABLE Classroom
DROP TABLE Faculty
DROP TABLE Rector
GO
*/

CREATE TABLE Rector(
	ID_rector INT PRIMARY KEY IDENTITY(1000,1),
	password_ varchar(16)
)
GO

CREATE TABLE Faculty(
	ID_faculty INT PRIMARY KEY IDENTITY(1,1),

	name_faculty VARCHAR(50)
);
GO

CREATE TABLE Classroom(
	ID_faculty INT CONSTRAINT FACULTY_FK_CLASSROOM REFERENCES Faculty(ID_faculty),

	ID_classroom INT PRIMARY KEY IDENTITY(1,1),
	classroom VARCHAR(3) NOT NULL,
	banches INT NOT NULL
)
GO

CREATE TABLE Career(
	ID_faculty INT CONSTRAINT FACULTY_FK_CAREER REFERENCES Faculty(ID_faculty),
	ID_career INT PRIMARY KEY NOT NULL,

	name_career VARCHAR(80),
	n_semester INT NOT NULL
);
GO

CREATE TABLE Teacher(
	ID_faculty INT CONSTRAINT FACULTY_FK_TEACHER REFERENCES Faculty(ID_faculty),
	ID_career INT CONSTRAINT CAREER_FK_TEACHER REFERENCES Career(ID_career),
	
	ID_teacher INT PRIMARY KEY IDENTITY(1,1),
	
	enrollment INT,
	middle_name VARCHAR(20),
	last_name VARCHAR(20),
	name_ VARCHAR(50),
	email VARCHAR(40),
	password_ VARCHAR(16),
	teacher_status VARCHAR(4)
)
GO

CREATE TABLE Student(
	ID_faculty INT CONSTRAINT FACULTY_FK_STUDENT REFERENCES Faculty(ID_faculty),
	ID_career INT CONSTRAINT CAREER_FK_STUDENT REFERENCES Career(ID_career),

	ID_student INT PRIMARY KEY IDENTITY(1000,1), -- Matricula

	middle_name VARCHAR(20),
	last_name VARCHAR(20),
	name_ VARCHAR(50),
	date_birth DATE,
	email VARCHAR(50),
	password_ VARCHAR(16),
	student_status VARCHAR(4)
);
GO

CREATE TABLE SemesterSubject(
	ID_faculty INT CONSTRAINT FACULTY_FK_SUBJECT REFERENCES Faculty(ID_faculty),
	ID_career INT CONSTRAINT CAREER_FK_SUBJECT REFERENCES Career(ID_career),

	ID_semester INT NOT NULL,
	ID_subject INT PRIMARY KEY IDENTITY(1,1),

	name_subject VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Schedule(
	ID_faculty INT CONSTRAINT FACULTY_FK_SCHEDULE REFERENCES Faculty(ID_faculty),
	ID_classroom INT CONSTRAINT CLASSROOM_FK_SCHEDULE REFERENCES Classroom(ID_classroom),
	ID_career INT CONSTRAINT CAREER_FK_SCHEDULE REFERENCES Career(ID_career),
	ID_teacher INT CONSTRAINT TEACHER_FK_SCHEDULE REFERENCES Teacher(ID_teacher),
	ID_subject INT CONSTRAINT SUBJECT_FK_SCHEDULE REFERENCES SemesterSubject(ID_subject),
	ID_schedule INT PRIMARY KEY IDENTITY(1,1),
	ID_group VARCHAR(MAX),
	schedule VARCHAR(MAX)-- UNAVAILABLE SCHEDULE
)
GO

CREATE TABLE Kardex(
	ID_faculty INT CONSTRAINT FACULTY_FK_KARDEX REFERENCES Faculty(ID_faculty),
	ID_career INT CONSTRAINT CAREER_FK_KARDEX REFERENCES Career(ID_career),
	ID_student INT CONSTRAINT STUDENT_FK_KARDEX REFERENCES Student(ID_student),
	ID_subject INT CONSTRAINT SUBJECT_FK_KARDEX REFERENCES SemesterSubject(ID_subject),

	ID_kardex INT PRIMARY KEY IDENTITY(1,1),
	
	op1 VARCHAR(3),
	op2 VARCHAR(3),
	op3 VARCHAR(3),
	op4 VARCHAR(3),
	op5 VARCHAR(3),
	op6 VARCHAR(3)
)
GO

CREATE TABLE StudentSchedule(
	ID_faculty INT CONSTRAINT FACULTY_FK_STUDENTSCHEDULE REFERENCES Faculty(ID_faculty),
	ID_classroom INT CONSTRAINT CLASSROOM_FK_STUDENTSCHEDULE REFERENCES Classroom(ID_classroom),
	ID_career INT CONSTRAINT CAREER_FK_STUDENTSCHEDULE REFERENCES Career(ID_career),
	ID_teacher INT CONSTRAINT TEACHER_FK_STUDENTSCHEDULE REFERENCES Teacher(ID_teacher),
	ID_student INT CONSTRAINT STUDENT_FK_STUDENTSCHEDULE REFERENCES Student(ID_student),
	ID_subject INT CONSTRAINT SUBJECT_FK_STUDENTSCHEDULE REFERENCES SemesterSubject(ID_subject),
	ID_schedule INT CONSTRAINT SCHEDULE_FK_STUDENTSCHEDULE REFERENCES Schedule(ID_schedule),
	ID_student_schedule INT PRIMARY KEY IDENTITY(1,1)
)
GO

CREATE TABLE Logs(
	ID_rector INT NULL REFERENCES Rector(ID_rector),
	ID_faculty INT NULL REFERENCES Faculty(ID_faculty),
	ID_classroom INT NULL REFERENCES Classroom(ID_classroom),
	ID_career INT NULL REFERENCES Career(ID_career),
	ID_subject INT NULL REFERENCES SemesterSubject(ID_subject),
	ID_student INT NULL REFERENCES Student(ID_student),
	ID_kardex INT NULL REFERENCES Kardex(ID_kardex),
	ID_teacher INT NULL REFERENCES Teacher(ID_teacher),
	ID_schedule INT NULL REFERENCES Schedule(ID_schedule),
	ID_student_schedule INT NULL REFERENCES StudentSchedule(ID_student_schedule),
	ID_logs INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	time_ TIME NOT NULL
)
GO



